#!/usr/bin/ruby
PATH = File.expand_path(File.dirname(__FILE__))

require PATH + "/../lib/r-solr.rb"


Outputter.limit 10 #how to change results limit

Terminal.clear

x = Query.new
y = Query.new

x << 'hello'
y << 'hello hi'

Scorer.new(x, y)

