#!/usr/bin/ruby
PATH = File.expand_path(File.dirname(__FILE__))

require File.expand_path("../../lib/solr-tweak.rb", __FILE__)


Outputter.limit 10 #how to change results limit

Terminal.clear

nothing =   Query.new
standard =  Query.new :request => TkiRequest


# y = Query.new

standard << 'educational leaders'
nothing << 'educational leaders'
# y << 'hello hi'

# Scorer.new(x, y)

