#!/usr/bin/ruby
PATH = File.expand_path(File.dirname(__FILE__))

require File.expand_path("../../lib/solr-tweak.rb", __FILE__)

if ARGV.length > 1
  raise "Too many arguments"
elsif ARGV[0] == nil
  raise "I need an argument"
else
  term = ARGV[0]
end




Outputter.limit 10 #how to change results limit

Terminal.clear

test =  Query.new :request => SCRATCH

test << term