#!/usr/bin/ruby
PATH = File.expand_path(File.dirname(__FILE__))

require File.expand_path("../../lib/solr-tweak/utils/trollop.rb", __FILE__)

opts = Trollop::options do
  opt :handler, "Select handler", :default => 'TKI_HANDLER'
  opt :verbose, "Print out full records", :default => nil
  opt :limit, "Limit results", :default => 10
	opt :explain, "Explain rankings", :default => nil
	opt :server, "Select server", :default => 'tki'
end

Trollop::die "I need a search term, at the very least" if ARGV.empty?

term = ARGV[0]
$limit = opts[:limit].to_s

require File.expand_path("../../lib/solr-tweak.rb", __FILE__)

begin
  handler = Kernel.const_get(opts[:handler])
rescue
  Trollop::die "Bad handler. See lib/solr-tweak/seeds/.."
end

$request_stub = 'http://' + SERVERS[opts[:server].to_sym] + '/solr/select?'

Terminal.clear

requester = Query.new :request => handler, :explain => opts[:explain] 

if opts[:verbose]
  requester.verbose term
else
  requester << term
end

